import Head from 'next/head'
import Image from 'next/image';
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillGithub, AiFillLinkedin } from "react-icons/ai";
import avatar from "../public/avatar.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import { useState } from 'react';


export default function Home() {
  const [ darkMode, setDarkMode ] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-800">
      <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl dark:text-white">Portfolio</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a className="bg-gradient-to-r from-cyan-500 to-cyan-600 text-white px-4 py-2 rounded-md ml-8" href="https://drive.google.com/file/d/11ap7DtiCsWexXOkYMMXLuw1cK1yrw4_s/view?usp=share_link">Resume</a>
              </li>
            </ul>
          </nav>

          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-cyan-600 font-medium">Ivan Godumanov</h2>
            <h3 className="text-2xl py-2 dark:text-white">Junior Front-End Developer</h3>
          </div>

          <div className="text-5xl flex justify-center gap-16 p-3 text-gray-600">
            <a href="https://github.com/facedrop" target="_blank">
              <AiFillGithub />
            </a>
            <a href="https://www.linkedin.com/in/ivan-godumanov-73881519a/" target="_blank">
              <AiFillLinkedin />
            </a>
          </div>

          <div className="relative mx-auto bg-gradient-to-b from-cyan-400 to-teal-400 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96" >
            <Image src={avatar} alt="avatar" layout="fill" objectFit="cover"/>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Service I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC</p>
          </div>

          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={design} alt="design" width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">Projects</h3>
              <p className="py-2 dark:text-white">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout</p>
              <h4 className="py-4 text-cyan-600 dark:text-white">Tools I use </h4>
              <p className="text-gray-800 py-1 dark:text-white">React</p>
              <p className="text-gray-800 py-1dark:text-white">NextJS</p>
              <p className="text-gray-800 py-1 dark:text-white">Tailwind</p>
              <p className="text-gray-800 py-1 dark:text-white">Bootsrap</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={code} alt="code" width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">Projects</h3>
              <p className="py-2 dark:text-white">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout</p>
              <h4 className="py-4 text-cyan-600 dark:text-white">Tools I use </h4>
              <p className="text-gray-800 py-1 dark:text-white">React</p>
              <p className="text-gray-800 py-1 dark:text-white">NextJS</p>
              <p className="text-gray-800 py-1 dark:text-white">Tailwind</p>
              <p className="text-gray-800 py-1 dark:text-white">Bootsrap</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={consulting} alt="consulting" width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">Projects</h3>
              <p className="py-2 dark:text-white">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout</p>
              <h4 className="py-4 text-cyan-600 dark:text-white">Tools I use </h4>
              <p className="text-gray-800 py-1 dark:text-white">React</p>
              <p className="text-gray-800 py-1 dark:text-white">NextJS</p>
              <p className="text-gray-800 py-1 dark:text-white">Tailwind</p>
              <p className="text-gray-800 py-1 dark:text-white">Bootsrap</p>
            </div>
          </div>
        </section>

        <section className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Portfolio</h3>
          </div>
          <div>
            <div className="basis-1/2 flex-1">
              <Image src={web1} alt="web1" className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
          </div>
          <div>
            <div className="basis-1/3 flex-1">
              <Image src={web2} alt="alt2" className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
          </div>
          <div>
            <div className="basis-1/3 flex-1">
              <Image src={web3} alt="alt3" className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
